name: Release

on:
  pull_request:
  push:
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=latest_tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
          echo "::set-output name=build_time::$(date -u +'%m-%d-%YT%H:%M:%SZ')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: trendyoltech/certificator:${{ steps.vars.outputs.latest_tag }}
          load: true
          build-args: |
            BUILD_TIME=${{ steps.vars.outputs.build_time }}
            VCS_REF=${{ steps.vars.outputs.sha_short }}
      - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v2
          with:
            version: latest
            args: release --rm-dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: docker push trendyoltech/certificator:${{ steps.vars.outputs.latest_tag }}